### ISSUE TITLE
Problem with Consolegrid API?

### ISSUE THREAD

**Issue by Jabnin** [scottrice/Ice#115]
Without doing anything to config.txt, Ice stopped downloading grid icons and gave me the following error 
![image](https://f.cloud.github.com/assets/5657058/1537065/d072d58e-4cbd-11e3-8d91-4ae8297ff3d1.png)

The site is up, so did I do something dumb, or is the API busted?

**Comment by weblets** [comment]
I have similar problems with Atari 5200 and the Wii Virtual Console
