### ISSUE TITLE
Xbox 360 Controller in Big Picture Mode

### ISSUE THREAD

**Issue by joeg77** [scottrice/Ice#159]
Is there a way to the Xbox 360 controller home button exit the games from running on the emulator?  It works with Nestopia, but not with Dolphin or Project64.  Any ideas on configuration? Or is this in the works for a future update?

**Comment by disparil** [comment]
Same problem here. Is there a way to exit the game (emulator) and return to Steam, with the Xbox button (guide) on the 360 Controller?

Thank you in advance!
