### ISSUE TITLE
New Banner Image Scraper Suggestion

### ISSUE THREAD

**Issue by closer2thelung** [scottrice/Ice#181]
I would like to suggest using the website http://thegamesdb.net/ as the image scraper for Ice. It seems to have a much more complete database than consolegrid.com. I am not smart enough to figure out how to implement this myself in my own configuration, but if anyone knows how please share the info.

here is a link to their api info if anyone is interested:
http://wiki.thegamesdb.net/index.php?title=Main_Page

**Comment by SonicBoom89** [comment]
Anyway i implemented a provider for thegamesdb.  
I solved the problem of the black borders by generating a fitting image using background blurring.

See my fork for an example
https://github.com/SonicBoom89/Ice/raw/master/ice-example-new.png
