### ISSUE TITLE
"Failed to launch (Game)"

### ISSUE THREAD

**Issue by samlegacy** [scottrice/Ice#189]
So i recently tried adding zsnes as my emulator on steam via ICE. Every one of the roms I have gives me this error whenever I try to launch from steam. "Failed to launch Super Mario World (USA)" or whichever game I'm currently attempting to launch.

My emulator.txt is as follows....

[ZSNES]
location=C:\Users\Blank\Documents\Emulators\zsnesw.exe
command=%l %r

Other than emulator.txt and console.txt I have not edited any other notepad documents so they are in their original state.

Any help would be greatly appreciated.
Thanks.

**Comment by scottrice** [comment]
Since there hasn't been a response I am going to close out the issue. @bgehrlein thanks for helping out, @samlegacy if you are still having problems feel free to reopen.

**Comment by ProtoBoyGG** [comment]
yes kind sir @scottrice  im having this problem also all games banners of snes games are of action 52 how to resolve this ??
