### ISSUE TITLE
Grid images with In Home Streaming

### ISSUE THREAD

**Issue by scottrice** [scottrice/Ice#202]
There have been reports that grid images don't appear when viewing a stream able game. Instead it displays the file path.

**Comment by scottrice** [comment]
If its not working for non-Ice shortcuts then I don't think there is anything I can do to fix the problem. As such, I am closing the task.

I hope Valve fixes this issue though. I can understand why they would want the client computer to be able to put in their own images, but I dont see any reason why they wouldn't get the custom images from the host computer by default if it has them.

**Comment by BlinksTale** [comment]
Scott, since you're mucking with pysteam anyways, can you see if there's a way to get the client to automatically grab images for all the remote games it picks up?

Steam lets you manually assign custom grid view images to streamed-only games from a client side, so there should be a way to access that in the code. I personally can't find it right now since it appears to not be in shortcuts.vdf or the games list there, but you may have more insight having worked with this library longer.

**Comment by scottrice** [comment]
> Steam lets you manually assign custom grid view images to streamed-only games from a client side, so there should be a way to access that in the code. I personally can't find it right now since it appears to not be in shortcuts.vdf or the games list there, but you may have more insight having worked with this library longer.

Ah, interesting. I have a theory on how this is working, and if I'm right then it should be totally doable to set grid images from a client machine. I won't elaborate too much more though because I haven't looked into it at all and I'm really just guessing.

The bigger problem is - how do I get Ice on the client to know about the Ice that is running on the server? Ice wasn't really meant to handle that use case. I could provide a way to keep Ice running in the background and provide an API for a client to read the list of games (and even the images from the host!)  but connecting the client Ice to the server Ice will be hard.

Once I get a streaming box of my own set up I'll try to work on some basic support for Steam In Home Streaming.

**Comment by BlinksTale** [comment]
Please elaborate! With your familiarity, even a guess is better than my best attempt, and might point me in the right direction. I'm happy to dive into the code myself.

Ice could definitely just run on both machines, and check whatever non-shortcuts.vdf file holds all those references, then assume they are all Ice games. I wish Tags were visible remotely, that would fix any confusion for that.
