### ISSUE TITLE
Python error code help please.

### ISSUE THREAD

**Issue by ELTANK01982** [scottrice/Ice#204]
![image](https://cloud.githubusercontent.com/assets/7996085/3398456/fe8bb88c-fd2f-11e3-9951-24cafffea5e0.jpg)

Hi can't seem to get ice to run, I think I'm nearly there. There are the error codes from Python if anyone can help please.

**Comment by benjick** [comment]
![image](https://cloud.githubusercontent.com/assets/430872/14753644/e832dfc0-08d6-11e6-8531-cbc9caff0609.png)

Having the same issue. File not there, added a custom shortcut to Notepad but didn't help.

Creating a blank `shortcuts.vdf` gives me `'NoneType' object is not iterable`

**Comment by geraldhumphries** [comment]
@benjick For now, you can try "Add a Non-Steam Game" to make Steam generate the shortcuts file.

**Comment by benjick** [comment]
> added a custom shortcut to Notepad

But the real problem was that that wasn't my SteamID, it picked up another one I guess so I removed all those folders that wasn't my SteamID and it worked.

**Comment by geraldhumphries** [comment]
@scottrice can you comment? I haven't been involved with the project for a long time so I'm not up to date on how it works.
