### ISSUE TITLE
Console Grid isn't down, but ice is reporting it as unavailable

### ISSUE THREAD

**Issue by Arkitan** [scottrice/Ice#211]
I'm getting the following error.

There was a problem with '[Grid Images] Cource' in config.txt The Source of game images is unavailable.

Here is my Grid Images section of config.txt

[Grid Images]
# The website listed should provide the grid images used by Ice. This URL will
# most likely need to be provided by the website itself, as it is fairly specific.
# 
# The default is ConsoleGrid (consolegrid.com/api/top_picture)
# 
# If this field is left blank, Ice will not attempt to download images

Source=consolegrid.com/api/top_picture

**Comment by Enverex** [comment]
There's a major problem with this which is stopping me from using it entirely. You use "Nickname" to denote the name of the folder that Ice will use for the games, but at the same time you use that same field to look up the images on ConsoleGrid which means that unless your game folders match the names that ConsoleGrid use, it won't work.

Can you please split out these two names into separate options as they're completely unrelated. My folders have specific names and I don't really want to rename everything to fit ConsoleGrid's own naming system.

**Comment by Tekkenjam** [comment]
what enverex said is the same for me. i already had rom and emulator files prior to learning of ices existence creating new sub folders and splitting all of them would be a major pain for me as it would reset alot of the configs i have set up for the games. I am having hte same issue as this thread

=========================Starting Ice
Detected Emulator: Snes9x
Detected Emulator: ePSXe
Detected Console: Playstation 1 => ePSXe
---------------Running for user 12923
---Downloading grid images
=========================Stopping

There was a problem with '[Grid Images] Source' in config.txt
The source of game images is unavailable.

**Comment by weblets** [comment]
Mhh I have a similar problem adding Atari to my console list. ICE simply breaks because gridImage does not support atari5200 as emulation nickname. Does anyone know of a solution?
