### ISSUE TITLE
Tag non-Ice shortcuts/games

### ISSUE THREAD

**Issue by fpiesche** [scottrice/Ice#249]
With the current behaviour, it's nice and easy to filter Big Picture view by console. What isn't possible is to get a view that only shows existing Steam games - the only option available here is "All Games" which shows *everything* including all the emulator shortcuts.

**Comment by fpiesche** [comment]
dibs! already working on this over on fpiesche/Ice.

**Comment by fpiesche** [comment]
This'll need modification to pysteam to make it able to see installed Steam games and shortcuts.

**Comment by scottrice** [comment]
I'm down with the modifications for pysteam. Could you make an equivalent issue on that repo? http://github.com/scottrice/pysteam/issues

As for the issue itself, I consider that out of the scope of Ice. Ice has one job - to add your ROMs as playable games. Library organization should be handled somewhere else.

That being said I've been thinking for a while that a general library-management tool for Steam could be useful. Things like automatically adding banners to games that you mark as 'played' or adding/removing tags from large numbers of games at once. That will have to be another project though, I want to keep Ice focused. On the bright side the code for the difficult problems I had to solve for Ice (reading/writing `shortcuts.vdf` and setting grid images for non-Steam games) all exists in pysteam, so theoretically it should be pretty straightforward to build on top of that.
