### ISSUE TITLE
setup.py fails on Arch Linux x64

### ISSUE THREAD

**Issue by ArcticVanguard** [scottrice/Ice#252]
Traceback (most recent call last):
      File "setup.py", line 72, in <module>
        requirements = [str(ir.req) for ir in parse_requirements('requirements.txt')]
      File "/usr/lib/python2.7/site-packages/pip/req/req_file.py", line 19, in parse_requirements
        "parse_requirements() missing 1 required keyword argument: "
    TypeError: parse_requirements() missing 1 required keyword argument: 'session'

This is all I get when I run

     python2.7 setup.py install

Being root doesn't make a difference, I have pip installed so I'm not sure what I'm doing wrong. The repository was just cloned today. Running it with just

    python setup.py install

defaults to using python 3.4. Contents of uname -a below:

    amelia@artemis~/g/i/Ice> uname -a
    Linux artemis 3.18.2-2-ARCH #1 SMP PREEMPT Fri Jan 9 07:37:51 CET 2015 x86_64 GNU/Linux

**Comment by scottrice** [comment]
Huh, thats really odd. Can you confirm that requirements.txt exists in that folder?

**Comment by ArcticVanguard** [comment]
Yup, got it right here.

    amelia@artemis~/g/i/Ice> ls
    config.txt    emulators.txt    icon.icns  LICENSE    requirements.txt  src/
    consoles.txt  ice-example.png  icon.ico   README.md  setup.py          tools/
    amelia@artemis~/g/i/Ice> cat requirements.txt 
    psutil==2.1.1
    appdirs==1.2.0
    pysteam>=0.1.3

**Comment by scottrice** [comment]
Ok, thanks. Not sure what the issue is, looks like I need to get myself an Arch Linux install.

Thanks for the report, I'll look into it.

**Comment by scottrice** [comment]
This issue should be fixed, but would you mind pulling the most recent version and checking to confirm?
