### ISSUE TITLE
Ubuntu 14.04 LTS 'python setup.py install' fails

### ISSUE THREAD

**Issue by ProfessorKaos64** [scottrice/Ice#255]
```
mike@mike-test2:~/Ice$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 72, in <module>
    requirements = [str(ir.req) for ir in parse_requirements('requirements.txt')]
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_file.py", line 19, in parse_requirements
    "parse_requirements() missing 1 required keyword argument: "
TypeError: parse_requirements() missing 1 required keyword argument: 'session'
mike@mike-test2:~/Ice$ 
```

Contents of requirements:

```
psutil==2.1.1
appdirs==1.2.0
pysteam>=0.1.3
```

Results of `sudo easy_install <target>`

```
Searching for psutil
Best match: psutil 2.2.0
Processing psutil-2.2.0-py2.7-linux-x86_64.egg
psutil 2.2.0 is already the active version in easy-install.pth

Searching for appdirs
Best match: appdirs 1.4.0
Processing appdirs-1.4.0-py2.7.egg
appdirs 1.4.0 is already the active version in easy-install.pth

Processing pysteam
Writing /home/mike/Ice/pysteam/setup.cfg
Running setup.py -q bdist_egg --dist-dir /home/mike/Ice/pysteam/egg-dist-tmp-mRs8JM
removing '/usr/local/lib/python2.7/dist-packages/pysteam-0.1.3-py2.7.egg' (and everything under it)
creating /usr/local/lib/python2.7/dist-packages/pysteam-0.1.3-py2.7.egg
Extracting pysteam-0.1.3-py2.7.egg to /usr/local/lib/python2.7/dist-packages
pysteam 0.1.3 is already the active version in easy-install.pth

```

Ice runs after I reran pysteam through these methods, but this is mighty confusing to folks who have no experience with this. Although the script noted it added my 2 SNES ROMs, there are not to be found in Steam. Steam was not running at the time.

```
INFO	 =========== Starting Ice ===========
INFO	 Detected Emulator: mednafen
WARNING	 [DISABLED] No emulator provided for console `Nintendo Entertainment System`
INFO	 Detected Console: Super Nintendo => mednafen
WARNING	 [DISABLED] No emulator provided for console `Nintendo 64`
WARNING	 [DISABLED] No emulator provided for console `Nintendo Gamecube`
WARNING	 [DISABLED] No emulator provided for console `Nintendo Wii`
WARNING	 [DISABLED] No emulator provided for console `Playstation 1`
WARNING	 [DISABLED] No emulator provided for console `Playstation 2`
WARNING	 [DISABLED] No emulator provided for console `Sega Genesis`
WARNING	 [DISABLED] No emulator provided for console `Sega Dreamcast`
WARNING	 [DISABLED] No emulator provided for console `Nintendo Gameboy`
WARNING	 [DISABLED] No emulator provided for console `Gameboy Advance`
WARNING	 [DISABLED] No emulator provided for console `Nintendo DS`
INFO	 =========== User: 21885827 ===========
INFO	 Adding ROM: `Kirby's Dream Land 3`
INFO	 Adding ROM: `Gokujou Parodius (Japan)`
INFO	 No image found for `Kirby's Dream Land 3`
INFO	 No image found for `Gokujou Parodius (Japan)`

Close the window, or hit enter to exit...

```

**Comment by scottrice** [comment]
Hey ProfessorKaos64. I think I fixed the saving issue yesterday, try pulling the most recent version of Ice.

The install issue is pretty troubling though. You are the second person who has had that issue in recent memory, and I have absolutely no idea why. Its interesting that it worked when you just `easy_install`d though. I'll look into this.

**Comment by scottrice** [comment]
Welp, google is my friend.

http://stackoverflow.com/questions/27869152/heroku-typeerror-parse-requirements-missing-1-required-keyword-argument-ses

Looks like a newer version of pip requires adding this keyword. Would you mind running `pip --version` and posting your output here to confirm?

I'll put a fix up soon.

**Comment by ProfessorKaos64** [comment]
Ok, I'll check on this when I get home or did you commit what was needed anyway?

**Comment by scottrice** [comment]
I committed anyway, but would you mind checking to confirm? Environment issues are always tricky, and the only environment I can test on is OS X so it would be super useful to see if my fix worked for you as well.

**Comment by ProfessorKaos64** [comment]
Hi @scottrice, things work fine now. `python setup.py install` requires sudo access it seems. Is that documented? The instructions for this project are in need of some work, but I should be good now. Thank you.

**Comment by scottrice** [comment]
That's definitely true. Keeping the readme up to date and wih good information is hard. Maybe I should use the wiki more.

With regards to sudo access - is that something you need to do 'pip install' normally or is that specific to Ice? Ice shouldn't need anything more than pip does, so if it's the later that's worrying.

**Comment by ProfessorKaos64** [comment]
I had to use sudo for the `python setup.py install` command or write access was denied for the installs. Ice itself was fine.

**Comment by scottrice** [comment]
Sorry, I should clarify. Do you need sudo access to do 'pip install appdirs'? Or for 'pip install psutil'? Or does it only require sudo access when you do it through 'python setup.py install'

**Comment by ProfessorKaos64** [comment]
I did not use pip, I used easy_install per the readme suggestion. I used sudo just for python setup.py install
