### ISSUE TITLE
Ice no longer works in SteamOS

### ISSUE THREAD

**Issue by sharkwouter** [scottrice/Ice#272]
I used to run Ice on SteamOS(Debian Wheezy with some packages from Valve), but it no longer seems to work. I get the same errors with both the upstream version and my fork, which used to work fine. It probably has to do with an upgrade to one of the packages in the system when compared to last year, but I'm not sure which one.

Here is the error I'm experiencing:

steam@steamos:~/Ice$ src/ice.py 
Traceback (most recent call last):
  File "src/ice.py", line 11, in <module>
    runner.run(sys.argv)
  File "/home/steam/Ice/src/ice/runners/command_line_runner.py", line 15, in run
    engine = IceEngine()
  File "/home/steam/Ice/src/ice/runners/ice_engine.py", line 46, in **init**
    self.users = self.steam.local_users()
  File "/usr/local/lib/python2.7/dist-packages/pysteam/steam.py", line 77, in local_users
    u = user.User(self, int(entry))
ValueError: invalid literal for int() with base 10: 'anonymous'

An error has occurred! A copy of the crash report has been saved to 'error.log'.
If this continues please submit an issue on our Github page (http://github.com/scottrice/Ice)

Here some additional info:
desktop@steamos:/home/steam/Ice$ pip search pysteam
pysteam                   - Python library to work with Steam
  INSTALLED: 0.1.3 (latest)
pysteamkit                - A library for working with Steam

desktop@steamos:/home/steam/Ice$ pip search appdirs
appdirs                   - A small Python module for determining appropriate
                            " +         "platform-specific dirs, e.g. a "user
                            data dir".
  INSTALLED: 1.4.0 (latest)

desktop@steamos:/home/steam/Ice$ pip search psutil
psutil                    - psutil is a cross-platform library for retrieving
                            information onrunning processes and system
                            utilization (CPU, memory, disks, network)in
                            Python.
  INSTALLED: 0.5.1
  LATEST:    2.2.1

I've also upgraded psutil to 2.2.1, but that didn't change anything.

**Comment by Gussi** [comment]
This issue was fixed in scottrice/pysteam@20071e5ea2faa5cda5681ed84b5ffe01d364291d - you could apply that patch manually.

@scottrice might need to bump up the version counter for pysteam so it updates, or something of that sort.

**Comment by HeroCC** [comment]
Same problem, except changing the config in the path doesn't work. I run ubuntu, and the workaround I used was to symlink ~/.local/share/Steam to ~/.steam

**Comment by sharkwouter** [comment]
This issue is about on old version of SteamOS and is no longer relevant. The amount of SteamOS users has also lowered so dramatically, that this is no longer worthwhile looking into.
