### ISSUE TITLE
Exiting games

### ISSUE THREAD

**Issue by aCoNdItE715** [scottrice/Ice#301]
How do I exit games with controller? Holding Select, then start doesn't work.  Using snes9x.  Do I have to download Joy2key? Is there any way to map it within snes9x?

**Comment by nileplumb** [comment]
Yes you'll need a way of sending keypresses like xpadder joy2key or pinnacle game profiler. I have xpadder and use a blank profile except for the select key which if I hold for 5 seconds sends alt+f4, some emulators may need a different combo, pcsx2 for example I use a profile that hits esc, waits 2 seconds then alt+f4

**Comment by aCoNdItE715** [comment]
Thanks for the help! I was hoping not to use joy2key but so far there's no way around it.  I wish snes9x would just build in xinput and a way to exit games on controllers.
