### ISSUE TITLE
Project64 - Shows up in Steam with Grid Icons Fine - "Attempt to Open File Failed" when pressing "Play"

### ISSUE THREAD

**Issue by rubyenmcc** [scottrice/Ice#303]
[Project64]
location=C:\Emulators\Project64 (N64)\Project64.exe
command=%l %r

[Nintendo 64]
nickname=N64
emulator=Project64

In notes

Ice scans and finds Grid Icons just fine.
Steam opens and shows icons and games just fine.
-
When pressing play, Project64 launches and I get an error "Attempt to Open File Failed"

This does not happen with any other Emulator.

**Comment by rubyenmcc** [comment]
Looks like in Steam, when going into the Game Properties
I see
"C:\Emulators\Project64 (N64)\Project64.exe" "C:\Emulators\ROMs\N64\CaliforniaSpeed.z64"

If I remove the "" C:\Emulators\ROMs\N64\CaliforniaSpeed.z64 and try to launch with Play, it works fine.

Though, how do I specify Ice to do this, so I'm not having to manually edit 50 N64 games properties in Steam?

Also, I am unable to launch into Full Screen? 

Any tips for a rookie?

**Comment by Foreverseeking** [comment]
I had the same issue, I almost gave up. 

I deleted the roms and re-added them using Ice and it worked... very odd. As for launching full screen, I set that within project 64 to be full screen and then on re-opening any of the roms it was still saved in that configuration.

**Comment by rubyenmcc** [comment]
Okay, so i fixed it.

I found that Scott has provided the Project64-launcher.exe tool.

I dropped the .exe in the Project64 folder.
Directed ice to use path for the launcher.
Now Steam is able to open the 64 titles with the customer launcher.
-
Works in full-screen as well.

Thanks Scott.

I'll close this issue.

If anyone needs more instructions, please let me know.

**Comment by Bboy486** [comment]
I was able to get it to launch but only the emulator. It does not launch a game by itself. 

Also, did you update both the emulator and console with the project4-launcher?
