### ISSUE TITLE
ICE not able to look at subfolders of ROMs?

### ISSUE THREAD

**Issue by xeroxpickles** [scottrice/Ice#312]
Unless I'm missing something in my set-up, it seems that ICE cannot look at subfolders within the ROM directory for individual games.

For example, if I have my folder setup as ~ROMS\Dreamcast\Sonic Adventure 2\Sonic Adventure 2.gdi

then ice will not be able to see that .gdi file. It has to be one directory up in the Dreamcast folder. But unfortunately a number of roms have files with duplicate, generic names (i.e. track01.bin) that require them to be stored in the same folder for the game to play properly.

Is their anyway to configure ice so that it looks within subfolders (as many levels as possible) for rom files?

**Comment by nileplumb** [comment]
Did this not fix it for you? https://github.com/scottrice/Ice/commit/8b82ae2b37844ac16c11667a2d91563eb4b38ce8

it's a development build, not a public binary release but works for my ps2 and wii games

**Comment by xeroxpickles** [comment]
Yes! That totally fixed it! Thanks for pointing that out nileplumb, much appreciated. Although now I've run into a separate issue where Demul won't run games from cmd line if they have spaces or underscores in the name, but you've gotten me one step closer!
