### ISSUE TITLE
Ice cant get grid images

### ISSUE THREAD

**Issue by Zabhahs** [scottrice/Ice#322]
Ice cant retrieve grid images, it looks like the site shut down or is under maintenance. Manual retrieval is fine, just annoying,

**Comment by lemonzap** [comment]
I'm having the same problem. Ice can't get the images and the search on consolegrid isn't working. I'm currently just manually searching through all the games under each console for the one I want but it take a little time to sort through all the games. At least they're alphabetized so that makes it a bit easier.

**Comment by Sibbs65** [comment]
I'm having the same issue.

**Comment by StormPooper** [comment]
Same, it looks as if the search for ConsoleGrid is down. According to scottrice/ConsoleGrid#34 the server may need restarting for ConsoleGrid.

**Comment by KodeAndGame** [comment]
Considering it's just search that's down, it might be possible to write a backup service that crawls consolegrid and provides it's own API that can be used by Ice. 

The most frictionless way to accomplish this might even be to leverage an existing search engine (e.g. google "bombastic ps2 site:consolegrid.com" but this doesn't seem to be 100% reliable so far. 

This solution would also require that a provider be written for Ice for this backup service. I'm looking into writing the backup service but don't think I'd be comfortable writing a provider for it yet.

**Comment by clairmont** [comment]
This is an issue for me too! 

http://consolegrid.com/api/top_picture

This appears to be bringing a rails server issue, so perhaps that is having issues while the main site is fine?

**Comment by TheCarterLilley** [comment]
Is there any word on this? Is there any way to reverse engineer the code to search http://steambanners.booru.org/index.php instead?

My library is a mess!

**Comment by KodeAndGame** [comment]
@TheCarterLilley - that should definitely be possible. Ice has support for a few existing sites and adding that one should be feasible. I'm not extremely familiar with Python but I'll do some investigation.

**Comment by TheCarterLilley** [comment]
That website would be absolutely perfect with Ice. I've manually downloaded the images for nearly 200 hundred games in the last 3 days through the booru. In all honesty, if we could get it to work, that should be default!

Sure would be a load of the developers neck, keeping the server up and what not.

**Comment by Sibbs65** [comment]
While we wait for this to come back up, does anyone know of a method to add
more games via ICE without having to re-add all of your custom game images
after ICE runs?

On Tuesday, December 29, 2015, TheCarterLilley <notifications@github.com>
wrote:

> That website would be absolutely perfect with Ice. I've manually
> downloaded the images for nearly 200 hundred games in the last 3 days
> through the booru. In all honesty, if we could get it to work, that should
> be default!
>
> Sure would be a load of the developers neck, keeping the server up and
> what not.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scottrice/Ice/issues/322#issuecomment-167938014>.
>


-- 
Brian Sibbel
Phone: (515)450-8861
Email: Bsibbel@gmail.com

**Comment by Bobesh8** [comment]
@KodeAndGame: Maybe have backup images stored in either Dropbox or Copy.

**Comment by TheCarterLilley** [comment]
this should meet the requirements! thanks!

**Comment by scottrice** [comment]
Hey guys, sorry for the delay. With the holidays and such I wasnt able to get to the computer I needed to be able to relaunch ConsoleGrid. Well I'm back home and ConsoleGrid should be back up and running. Let me know if you run into more issues.

**Comment by mystrokapp** [comment]
Hey @scottrice,

Thanks so much for getting ConsoleGrid up and running again. Unfortunate, now Ice is telling me "The image provider has no game called [insert title here]. Try going to consolegrid.com and submitting the game yourself" for every title in Ice. Is this a related problem? Should I start another issue for this error?
