### ISSUE TITLE
Console Grid Down!

### ISSUE THREAD

**Issue by Ezraiel92** [scottrice/Ice#324]
The api for console grid is down. Ice won't download any images, just brings up console grid errors.

**Comment by seriosbrad** [comment]
Would like to confirm this issue. First time trying Ice and it appears this issue has been going on for a couple weeks unnoticed :(

**Comment by StormPooper** [comment]
This is indeed the case - see #322 and scottrice/ConsoleGrid#34. No word from @scottrice yet on a potential fix.

**Comment by scottrice** [comment]
I'm aware of the issue, but due to some technical problems and the holidays I'm unable to get a fix out currently. Please use the issue that @StormPooper linked for other requests. Sorry for the inconvenience.
