### ISSUE TITLE
no such file path src/ice.py

### ISSUE THREAD

**Issue by andrewowen** [scottrice/Ice#326]
In the Set Up instructions it says to run Ice, you just need to run the command

```
python src/ice.py
```
I simply get
```
C:\Users\Andrew\Desktop\Ice (master)
λ python src/ice.py
python: can't open file 'src/ice.py': [Errno 2] No such file or directory
```
but this doesn't exist. I'm a little new to programming so any pointers on what I'm missing would be great.

**Comment by futurepr0n** [comment]
Hey - I had the same issue before, it looks like the new instruction should be to open CMD to your ICE directory, and run "python ice"
It should treat the ice/ directory as a python file and begin runnin the ICE scripts.. I have an issue though thats one above yours right now, where something is crapping out on me in my Ubuntu set up. 

Let me know if you get further now!

**Comment by andrewowen** [comment]
Hey thanks for your help! that definitely clears things up.
I got further but I look to be having the same issue as you, though on windows 10 and not ubuntu.
```
C:\Users\Andrew\Desktop\Ice (master)
λ python ice
=========== Starting Ice ===========
Detected Emulator: SNES9X
Detected Console: Super Nintendo => SNES9X
=========== User: 67072185 ===========
[ERROR] An exception occurred while running Ice
Traceback (most recent call last):
  File "ice\runners\ice_engine.py", line 154, in run
    self.main(dry_run=dry_run)
  File "ice\runners\ice_engine.py", line 134, in main
    self.run_for_user(user_context, dry_run=dry_run)
  File "ice\runners\ice_engine.py", line 146, in run_for_user
    self._create_backup(user, dry_run=dry_run)
  File "ice\runners\ice_engine.py", line 164, in _create_backup
    shortcuts.write_shortcuts(backup_path, shortcuts.get_shortcuts(user))
  File "C:\Python27\lib\site-packages\pysteam-1.0.0b1-py2.7.egg\pysteam\shortcuts.py", line 38, in get_shortcuts
    return read_shortcuts(paths.shortcuts_path(user_context))
  File "C:\Python27\lib\site-packages\pysteam-1.0.0b1-py2.7.egg\pysteam\shortcuts.py", line 27, in read_shortcuts
    return ShortcutParser().parse(path)
  File "C:\Python27\lib\site-packages\pysteam-1.0.0b1-py2.7.egg\pysteam\_shortcut_parser.py", line 19, in parse

    raise IOError("Shortcuts file '%s' does not exist" % path)
IOError: Shortcuts file 'c:/program files (x86)/steam\userdata\67072185\config\shortcuts.vdf' does not exist

Close the window, or hit enter to exit...
```

I wonder what is going on?

**Comment by futurepr0n** [comment]
Now we hang tight!

**Comment by Andre-Oliveira** [comment]
On Linux i went around that error by creating the file using the "toutch" command if Windows doesn't have something like this you can try to create an empty .txt file and change the extension.

**Comment by scottrice** [comment]
Hey everyone,

You're right that I removed `src/ice.py` in order to rearrange my code structure. The new way of running it (as @futurepr0n alluded to) is `python -m ice`. I commited f415c277f4bff03cec1dfa21eb9af0e85b39ca1f to fix the issue.

For @andrewowen, thats actually an issue with pysteam that I fixed for my work locally but which I hadn't pushed to Github. I just pushed 6878314668b23e1b21eaf6ef21a24d51107ed100 to fix that though, so if you run `python setup.py install` again then you should be able to run Ice as normal.

Thanks for your patience everyone.

**Comment by andrewowen** [comment]
Thanks for your reply and fixes @scottrice . Will give it a shot tonight

+1

**Comment by futurepr0n** [comment]
Can we re-open this issue? I tried to go through the process again, but am stl getting the same issue with the backups directory. Which is odd considering I tried taking that section out completely from the config.txt

futurepr0n@futureMedia:~/Ice$ sudo python -m ice
/usr/lib/python2.7/dist-packages/pkg_resources.py:1031: UserWarning: /home/futurepr0n/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
=========== Starting Ice ===========
Detected Emulator: Dolphin
Detected Emulator: PCSX2
Detected Console: Nintendo Gamecube => Dolphin
Detected Console: Playstation 2 => PCSX2
=========== User: 2267067 ===========
[ERROR] An exception occurred while running Ice
Traceback (most recent call last):
  File "ice/runners/ice_engine.py", line 154, in run
    self.main(dry_run=dry_run)
  File "ice/runners/ice_engine.py", line 134, in main
    self.run_for_user(user_context, dry_run=dry_run)
  File "ice/runners/ice_engine.py", line 146, in run_for_user
    self._create_backup(user, dry_run=dry_run)
  File "ice/runners/ice_engine.py", line 164, in _create_backup
    shortcuts.write_shortcuts(backup_path, shortcuts.get_shortcuts(user))
  File "/usr/local/lib/python2.7/dist-packages/pysteam-1.0.0_beta1-py2.7.egg/pysteam/shortcuts.py", line 31, in write_shortcuts
    with open(path, "w") as f:
IOError: [Errno 2] No such file or directory: '/home/futurepr0n/.config/ice/Backups/2267067/config/shortcuts.20160125174051.vdf'

Close the window, or hit enter to exit...
