### ISSUE TITLE
Add .replace() for quoted_cfg

### ISSUE THREAD

**Issue by piccaruse** [scottrice/Ice#328]
In the case of PCSX2, many games require separete configuration files. These can be set using the cfgpath="" and cfg="" launch options, using %r returns the extension iso and pcsx2 of course does not boot trying to parse the iso for configs. Another string for the path to and/or name without path to config files with maybe configurable extensions? 

In more simple words, I'd like my 
`command=%l %r --fullscreen --nogui --cfgpath=%p --cfg=%c` 

or what ever the expressions would be, to become: 

`"/usr/bin/PCSX2" "/home/user/roms/ps2/rom.iso" --fullscreen --nogui --cfgpath="/home/user/roms/ps2/cfg/" --cfg="config.cfg"` 

after parsing.

**Comment by scottrice** [comment]
This seems totally reasonable, but I'm confused on what exactly you need the command format to supply. It seems like the `cfgpath` would be the same for everything, so really what you need is to pass something like `--cfg="%n.cfg"` where `%n` would give you the unquoted name of the ROM? Does that sound around right?

**Comment by piccaruse** [comment]
Don't be confused, you got it right. I'm making it more complicated than it needs be. Just the file name without an extension as a %-string would be nice. I could probably get it in a pull request for you so you don't have to worry about it.

**Comment by piccaruse** [comment]
Made a pull request https://github.com/scottrice/Ice/pull/331

**Comment by scottrice** [comment]
Pull request has been merged, so closing this out. Thanks for adding this feature.
