### ISSUE TITLE
No such file or directory Windows 10

### ISSUE THREAD

**Issue by Calvin149** [scottrice/Ice#340]
When I try to run Ice it gives me this error:

=========== Starting Ice ===========
Detected Emulator: Dolphin
[WARNING] No emulator provided for console `Nintendo Entertainment System`
[WARNING] No emulator provided for console `Super Nintendo`
[WARNING] No emulator provided for console `Nintendo 64`
[WARNING] No emulator provided for console `Nintendo Gamecube`
Detected Console: Nintendo Wii => Dolphin
[WARNING] No emulator provided for console `Playstation 1`
[WARNING] No emulator provided for console `Playstation 2`
[WARNING] No emulator provided for console `Sega Genesis`
[WARNING] No emulator provided for console `Sega Dreamcast`
[WARNING] No emulator provided for console `Nintendo Gameboy`
[WARNING] No emulator provided for console `Gameboy Advance`
[WARNING] No emulator provided for console `Nintendo DS`
=========== User: 104983822 ===========
[ERROR] An exception occurred while running Ice
Traceback (most recent call last):
  File "ice\runners\ice_engine.py", line 153, in run
    self.main(dry_run=dry_run)
  File "ice\runners\ice_engine.py", line 133, in main
    self.run_for_user(user_context, dry_run=dry_run)
  File "ice\runners\ice_engine.py", line 145, in run_for_user
    self._create_backup(user, dry_run=dry_run)
  File "ice\runners\ice_engine.py", line 167, in _create_backup
    shortcuts.write_shortcuts(backup_path, shortcuts.get_shortcuts(user))
  File "C:\Python27\lib\site-packages\pysteam-1.0.0_beta2-py2.7.egg\pysteam\shortcuts.py", line 31, in write_shortcuts
    with open(path, "w") as f:
IOError: [Errno 2] No such file or directory: u'C:\\Users\\Calvin\\AppData\\Local\\Scott Rice\\Ice\\Backups\\104983822\\config\\shortcuts.20160112145709.vdf'

Close the window, or hit enter to exit...

**Comment by sharkwouter** [comment]
There is a pull request to fix this here: https://github.com/scottrice/Ice/pull/334
