### ISSUE TITLE
Ice github page broken when viewed with https

### ISSUE THREAD

**Issue by opcon** [scottrice/Ice#342]
When I view the Ice homepage/faq/guide with https I am unable to expand faq questions and emulator guides.

I think this is due to the following error in the javascript console: 

```
Mixed Content: The page at 'https://scottrice.github.io/Ice/faq/' was loaded over HTTPS, but requested an insecure script 'http://code.jquery.com/jquery.js'. This request has been blocked; the content must be served over HTTPS.
```

An easy fix (I believe) would be to change the jquery library location from `http://code.jquery.com/jquery.js` to `https://code.jquery.com/jquery.js`.

**Comment by scottrice** [comment]
@zekesonxx Fixed this with PR #350
