### ISSUE TITLE
Can't run Higan from Big Picture

### ISSUE THREAD

**Issue by Sureiya** [scottrice/Ice#353]
I have a pretty weird issue that I can't figure out.

I have Higan setup to run SNES games along with a single rom (Chrono Trigger in sfc format).

When I run the shortcut through the steam client, everything works fine.

When I try to run the game through big picture, higan starts up but doesn't load the rom (No Cartridge Loaded).

I've checked the exact command being run with Process Explorer, and it seems to be the same both times. I can't figure out what is different.

**Comment by scottrice** [comment]
Hmmm... thats very odd. Is this a problem with Ice though? It sounds like Higan might need some command line funkiness to get working, but from your description it seems like Ice is functioning correctly. Ice's only job is to get the ROMs added to Steam using the command in `emulators.txt`, unless Ice messing with the command is causing your problems (not impossible, but unlikely given that desktop mode works) I don't know if theres anything I can do to fix this.

Thanks for reporting though, and let me know if you find a solution.

**Comment by Roet-Ivar** [comment]
Hi guys.
I also have this problem. I only gor roms to load if I added/generated a minifest through icarus.exe. And then (let's take) "batman returns.nes" that is placed in D:\Roms\nes\, in steam I have change the launch properties to "D:\Emulators\higan\higan-balanced.exe" "D:\Roms\Famicom\batman returns.fc".
Is there anyway to just pass the real filename as argument to Higan instead?

Thanks for an excellent emulator!
