### ISSUE TITLE
Can we upgrade emulator versions?

### ISSUE THREAD

**Issue by podonnell319** [scottrice/Ice#356]
Hello,

I installed this package awhile ago and have not used it for a long time. I started playing a game the other day that uses PSCX2, but the version I have is 1.0 for PSCX2 itself. Is there a specific procedure for replacing this with a newer PSCX2 version, or is the 1.0 version required to run Ice?

Could I simply grab the installer for a newer version and then transfer those assets into the directory where the emulators are?

Thanks for any info.

**Comment by ProfessorKaos64** [comment]
Ice doesn't install emulators. You need to update PCSX2 itself from your OS / Distro's repositories.

**Comment by nileplumb** [comment]
@ProfessorKaos64 it used to install/download them too if you wanted.
@podonnell319 you should be fine unzipping the new nightly builds over the current directory replacing the the files, it's what I do for my emulators like dolphin and pcsx2

**Comment by scottrice** [comment]
As @ProfessorKaos64 mentions, Ice no longer manages emulators. That ended up being too restrictive for most people, and finding a set of emulators that fit everyones needs was outside of the scope of Ice (and also outside of my area of expertise :P). Now Ice just focuses on what its good at - adding shortcuts to Steam.

Anyway, what @nileplumb suggested is your best bet for getting newer emulators on your version of Ice. Alternatively, you can upgrade Ice and set up whatever emulators you want, but whether you want to do that or not is up to you.

There isn't anything actionable for me in code here, so I'm going to close out the issue. Let me know if theres anything else I can help you with.
