### ISSUE TITLE
Ice not adding ROMs to Steam

### ISSUE THREAD

**Issue by mustangman101** [scottrice/Ice#359]
It says 

=========== Starting Ice ===========
Detected Emulator: Dolphin
Detected Emulator: PCSX2
Detected Emulator: FCEUX
=========== User: 144941230 ===========
=========== User: 26 ===========

Close the window, or hit enter to exit...

Once it does that it doesn't add any of the games to Steam although it recognized the emulators...

**Comment by LonelyTVy** [comment]
Make sure you have added your ROMs directory correctly under the [Storage] section in "config.txt", also ensure that your "consoles.txt" is also correctly configured for each console and emulator pair.

**Comment by mustangman101** [comment]
Now I changed that and the [Steam] bit cause I put Steam on my D: drive but now this is what it brings up

=========== Starting Ice ===========
Detected Emulator: Dolphin
Detected Emulator: PCSX2
Detected Emulator: FCEUX
Detected Console: Nintendo Gamecube => Dolphin
Detected Console: Sony Playstation 2 => PCSX2
Detected Console: Nintendo Entertainment System => FCEUX
=========== User: 144941230 ===========
=========== User: 26 ===========

Close the window, or hit enter to exit...

**Comment by LonelyTVy** [comment]
So, it looks like it's finding the emulators and "pairing" it up with your console of choice. What does your [Storage] section look like in "config.txt"?

**Comment by mustangman101** [comment]
I have this as the master folder as my C: drive is very small, almost everything is on my D: drive. But, it looks like this 

[Storage]
# The path to place your ROMs Directory. This can be in any drive or anywhere,
# as long as the full path is specified. Use ~ to represent your home folder
# (for example, C:\Users\Scott\)
#
# Set a directory where the ROMs are stored.
# If no directory is provided, "~/ROMs" is used.
# Example:
# ~\ROMs                     => C:\Users\<YOUR USERNAME>\ROMs
# ROMs Directory= D:\Steam ROMS

I have subfolders in the steam roms for each console

**Comment by LonelyTVy** [comment]
The subfolders is what's causing you issues. I'm assuming you are using the version of ICE downloaded from the homepage? If so it's an older version and doesn't support, as far as I know, the newer "consoles.txt" that has options for subfolders. 

Currently I can't get ICE 1.0 working due to a bug. Scott mentioned he would fix it sometime soon, so if you can wait for it that would be the best option. Otherwise, you can test it out by moving the ROMs you want into the root of your ROMs folder and let ICE add them. In the meantime you can download this "console.txt" from the GIT page and configure it for the newer version.

**Comment by mustangman101** [comment]
Well, I took out the subfolders and it's doing the same thing. I guess I'll just wait for him to update it.

**Comment by scottrice** [comment]
@mustangman101 How are you running Ice? Can you run the command `Ice.exe pdebug`? That will post your debug logs to pastebin. Please comment with the resulting URL and I can take a look.

**Comment by mustangman101** [comment]
I'm just double clicking the ice.exe in the ice folder that I downloaded, also I have 1.0 version. and no I don't really understand what you mean by run ice.exe pdebug. I assume you mean in the command prompt but I'm not positive.

**Comment by scottrice** [comment]
@mustangman101 Yup, thats what I mean. Open `cmd.exe`, `cd` into the directory with Ice, and run `Ice.exe pdebug`. Alternatively, you can right click on `Ice.exe`, hit "Create Shortcut", then on the resulting shortcut right click and hit "Properties", and under "Target" where it says `C:\Path\to\Ice.exe` just add `pdebug` afterwards (so it says `C:\Path\to\Ice.exe pdebug`). Then you can double click the shortcut instead.

Anyway, from looking at what you've posted so far, it looks like you have your consoles/emulators set up correctly (we can see that Ice has detected them and mapped them), so my guess is that its having trouble actually finding any of your ROMs. Can you explain to me what your ROMs directory looks like? You mention its `D:\Steam ROMs`. Inside there should be a subdirectory for every console (in this case, an `NES`, a `Gamecube`, and a `PS2` directory), what are the contents of those directories?

**Comment by mustangman101** [comment]
The pastebin is far longer than I imagined and has mostly useless stuff I think but... http://pastebin.com/D0Vatjud

And I have a subfolder inside D:\ Steam ROMs with the .isos/.nes/.gcm/.bin for all the games

**Comment by drglove** [comment]
You've left your ROMs directory commented out in your config file.
`# ROMs Directory= D:\Steam ROMS`

Change this to `ROMs Directory= D:\Steam ROMS` (i.e. remove the #).

**Comment by mustangman101** [comment]
@drglove THANK YOU SO MUCH that one simple thing was all it took...

**Comment by scottrice** [comment]
Commenting out the `ROMs Directory` option seems to have left a lot of people confused. I think I need to change that...

Anyway, I'm glad that things got sorted out for you. Thanks for helping out as well @drglove  and @LonelyTVy

**Comment by vvvvkennyvvvv** [comment]
im having this problem still i have tried everything and it wont add my roms to steam here is a copy of my config file 

# Set a directory where the ROMs are stored.
# If no directory is provided, "~/ROMs" is used.
# Example:
# ~\ROMs                     => C:\Users\<YOUR USERNAME>\ROMs
ROMs Directory=C:\Users\Classic Games\SNES 
and here is my other one 
[zsnes]
location=C:\Users\Classic Games\Emulators\zsnesw.exe
command=%l %r

**Comment by skataneric** [comment]
When you run ICE it will look for or create folders based on the "nickname=" you set in the consoles.txt. Make sure your ROMs are in those folders... or change the nickname to match the folders you made. I ran into an issue where it was only recognizing a couple consoles. So I checked my ROM folder and I saw that ICE had made empty folders. When I moved my ROMs to those and re-ran it saw them all.

**Comment by tglaesmann** [comment]
I have the same issue. If I open steam and delete all of the rom shortcuts then ICE is successful the next time I run the application. If I do not, and wish to install a new rom by copying it into the appropriate directory and running ICE then I get an error message and the new shortcut is not added.
