### ISSUE TITLE
Periods in ROM filenames yield incorrect shortcut names

### ISSUE THREAD

**Issue by drglove** [scottrice/Ice#364]
Commit: https://github.com/scottrice/Ice/commit/5000749fd68c6fa7356ad38a75d148527d216ef6
When a ROM contains a '.' in the filename, it seems that the parsing of the filename stops.
For example, **Dr. Mario 64.z64** puts the shortcut name as **Dr** with no text following.

I would suspect that it is trying to strip off the extension but this is being handled incorrectly.

**Comment by drglove** [comment]
It looks like it's caused by the regex string used here: https://github.com/scottrice/Ice/blob/5000749fd68c6fa7356ad38a75d148527d216ef6/ice/parsing/rom_parser.py#L10-L15

**Comment by scottrice** [comment]
Ah, good find. Thanks for the report! Adding an example name also helps a lot, I'll work on getting this fixed.

**Comment by drglove** [comment]
Looks good @scottrice, can I close my pull request https://github.com/scottrice/Ice/pull/365?
