### ISSUE TITLE
Filename period parser problem

### ISSUE THREAD

**Issue by saftle** [scottrice/Ice#370]
Ever since the filename parser was put into place, everything after the first period is removed from the filename. I think it should instead remove everything after the last period. Games like "Dr. Mario", are instead being changed into "Dr".

Thanks for your works guys.

**Comment by scottrice** [comment]
I'm pretty sure I fixed this already in 815888c90c243be9c9a3b8ee25685b77c9d725df. I included a test case for Dr Mario specifically (https://github.com/scottrice/Ice/blob/master/tests/rom_parser_tests.py#L25), are you using the most updated version? If you have another test case I can definitely include it.

**Comment by saftle** [comment]
Oh, I think I may be on the newest windows stable release, rather than from source. Thanks for the update!
