### ISSUE TITLE
Automatically stores backups in home folder: ~/Ice/backups

### ISSUE THREAD

**Issue by Jimi-James** [scottrice/Ice#374]
I don't like having to move this folder somewhere else manually every time. Why can't it just store the backups in the current working directory, or a user-specified one, instead of always having to be an Ice folder than I don't want in my home folder?

**Comment by scottrice** [comment]
You can configure the backups directory in config.txt.

Although you're right that we should default to a better location. Will fix.

**Comment by Jimi-James** [comment]
Oh, I'm dumb. How did I miss that?
