### ISSUE TITLE
Can you run emulators such as PCSX2 with individual configs (inis etc)

### ISSUE THREAD

**Issue by asatormk** [scottrice/Ice#389]
Hi Scottrice,

First of all, I want to say thank you for your program. I've just come from using Rocketlauncher & Hyperspin, and I can say for me it wasn't worth the heartache (Rocketlauncher module updates killed my setup and I don't feel like all that again)

I've looked around and I cant find an answer to this question - is it possible to have Ice run different configurations for different games? Maybe a line of script that designates a folder with the same name as the rom which holds INIs

I'm not a pro at any of this and I'm kinda speaking with ignorance, so forgive me. Mainly I want PCSX2 to work with different INI configs as so many games for PCSX2 need different settings.

**Comment by eatnooM** [comment]
I've just had a look at http://wiki.pcsx2.net/index.php/Command-line_support and it looks like `--cfg="CFGFile"` is what you're looking for - you could use this in conjunction with the `%fn` parameter introduced in https://github.com/scottrice/Ice/pull/331 to point PCSX2 to a config with the same name as the game. So if your emulators.txt entry for PCSX2 looks something like:

```
[PCSX2]
location=C:\PCSX2\pcsx2.exe
command=%l %r --nogui --cfg="%fn.cfg"
```

A quick test suggests that the path will resolve relative to C:\PCSX2\ in the above, so your config files should reside in the same folder as the PCSX2 executable.

Be sure you're using release 1.0.0! I found out about the project yesterday and was using a version from 2013 linked from the site which didn't support `%fn`.

**Comment by asatormk** [comment]
Thanks so much for your time and help. Much appreciated! I'll give this a whiz as soon as I have time.
