### ISSUE TITLE
Shortcuts won't open

### ISSUE THREAD

**Issue by elliebelliebooh** [scottrice/Ice#416]
I've had big problems with both pcsx2 and ice, both yesterday and today, but those problems were fixable. 

Now I've got a new problem that has been super annoying for hours....
It happened after the new Windows update though.

Everything in Ice is as it should be, all the .txt files are correct (in my opinion) and Ice adds the titles of the games to steam, but with a folder for icon. And when I try to open it just open the correct pcsx2 directory window.. I've tried to change the "startup location" in steam but without success :(

Please help, I'm going mental over here

**Comment by nateberkopec** [comment]
@elliebelliebooh what fixed the issue for you?

**Comment by elliebelliebooh** [comment]
@nateberkopec actually, just removing the shortcuts from Steam, getting mad at my computer and restarting everything, and launching ICE again and then it just worked 👍
