### ISSUE TITLE
ICE CMD windows closes imediatly, log says that it started and nothing else

### ISSUE THREAD

**Issue by Skidtastic** [scottrice/Ice#418]
I have made changes to the config , consoles, and emulator files. they all look correct. when I start ICE the cmd window appears for a second then closes immediately and I can't see what issues its having. the log file says [11/11/16 16:52:48] =========================Starting Ice 
and that's it....any ideas?

**Comment by Skidtastic** [comment]
sorry was some parsing errors , working now

**Comment by nateberkopec** [comment]
👍 Please close the issue if the problem has been resolved.
