### ISSUE TITLE
Ice not able to find Roms 2 or more subfolders deep

### ISSUE THREAD

**Issue by HEspoke** [scottrice/Ice#453]
Although the latest developmental build of ICE allows for the Romfinder to find roms in a subfolder. ICE can not look for roms deeper then that one subfolder. The problem arises when a Rom needs to be kept in a folder structure that has multiple subfolders in order to work properly. The Loadline format for Wii U games is exactly the problem I am referring to. ICE can not find Loadline formatted games for Wii U because they require that the "ROM" file be within a subfolder. I hope someone can fix this so that we can add Wii U games to the ICE romfinder functions. Loadline is the the most popular way that Cemu finds and runs Wii U games.

**Comment by screwattackthis** [comment]
Project unfortunately doesn't look to be maintained by anyone at the moment.  I want this too so I'll take a look at it and see if it's doable.

**Comment by HEspoke** [comment]
Cool, let me know if you make some progress on it @screwattackthis

**Comment by HEspoke** [comment]
#473 Issue resolved by switching to SRM.
