### ISSUE TITLE
Ice Force Close

### ISSUE THREAD

**Issue by jelliszipwhip** [scottrice/Ice#454]
Hello,

I am attempting ICE for the first time.  I feel like I have things set up correctly.  However, ICE will not open.  I double click the .exe, the prompt very quickly opens, and then automatically closes.  I am running on Windows 8.1.  PLEASE help!!!

**Comment by jelliszipwhip** [comment]
I'm not sure if I have to have a Steam Link.  I am attempting to do this on an Alienware Alpha.

**Comment by HEspoke** [comment]
@jelliszipwhip you do not have to have a Steam Link. I used to have a Alpha and had ICE running fine on it.  Where did you download ICE from? It should run if you have the windows install package and then stop to tell you the error. It will also stop when it completes successfully to tell you its done. If the window is closing then your probably dont have the right ICE files.

**Comment by jelliszipwhip** [comment]
@HEspoke Sorry that I tagged you in the other post.  I wasn't paying attention to where I was :) 

I downloaded ICE from https://scottrice.github.io/Ice/

It looks like the version I downloaded was last modified in 2013.. Is there a newer version that I should be using?

It installed fine, and unzipped fine.  I was able to edit the config.exe, emulators.exe and consoles.exe.  After completing those edits, I went to open ICE.exe, and it opens for a brief second, and then closes.  I fought with it until early into the morning this morning....

**Comment by jelliszipwhip** [comment]
![screenshot 3](https://cloud.githubusercontent.com/assets/26666252/24326811/d3203d6c-117c-11e7-843f-f178afaa3997.png)

I was able to quickly time a screen shot when it opens, and then closes..

**Comment by jelliszipwhip** [comment]
![screenshot 6](https://cloud.githubusercontent.com/assets/26666252/24326822/003f32d0-117d-11e7-8af6-8e83b123cbee.png)

I was able to quickly pull a screenshot while it opened and closed..

**Comment by jelliszipwhip** [comment]
![capture](https://cloud.githubusercontent.com/assets/26666252/24326835/61bb395a-117d-11e7-9074-c2dd8574768f.PNG)

I was able to grab the screen before it force closed.. Good timing.

**Comment by jelliszipwhip** [comment]
I think I have it pinned down to something wrong in the "console.txt" file.  When I edit only "config" and "emulators" ICE launches with this error.. 
![no error](https://cloud.githubusercontent.com/assets/26666252/24327071/dd93f8ea-1183-11e7-81d4-55fa97df2cd2.PNG)

When I move my edited "console.txt" file into the ICE file, it force closes.  This is my "console.txt" file..

![consoles](https://cloud.githubusercontent.com/assets/26666252/24327075/fa54aef2-1183-11e7-83e8-063977a6aab4.PNG)

I really appreciate any help.

**Comment by jelliszipwhip** [comment]
I was wrong.  It force closes when consoles.txt and config.txt are in the same ICE file together.  If I have any other combo (consoles, emulators or emulators and config) it opens with an error.  Whenever I get consoles and config in the same file, I get a force close.

**Comment by jelliszipwhip** [comment]
Holy shit, I did it.
