### ISSUE TITLE
Consolegrid site expired

### ISSUE THREAD

**Issue by vereis** [scottrice/Ice#464]
consolegrid.com is expired.

**Comment by baker-james** [comment]
Getting this too. Are there any trusty download alternatives?

**Comment by hrhnick** [comment]
http://retrogaming.cloud supports the ICE api. You can add "Source=retrogaming.cloud/api/v1/game/mostPopular" to your config. You can also manually search and download the images and have ICE scrape locally for them, this gives you the greatest control.

**Comment by Sluggies** [comment]
Uh, we need the ice.zip, not just the images :/

**Comment by vereis** [comment]
Unlike Consolegrid though, you need to ensure your games can be found and have images on [retrogamingcloud](http://retrogaming.cloud) or Ice won't work.

In my testing, retrogamingcloud has quite a few images so it isn't a problem but since the site as far as I can see has no easy search barring a global search, it can be quite a pain depending on how your games were named.

I only had this issue though because a few of my games were named slightly off and used custom images.

**Comment by Sluggies** [comment]
I mean, some of us need the download for it :/

**Comment by baker-james** [comment]
Yeah, wanted to use Ice to create Steam Library shortcuts. I've got 120gb of game files, a manual adding job isn't really feasible.

A workaround for now is a single shortcut in the Library to EmulationStation (or similar). It would be nice to be directly in the Steam Library though.

**Comment by ScottSteiner** [comment]
A workaround for the download is to use an archived copy at https://web.archive.org/web/20151028164620/http://consolegrid.com/ice.zip

**Comment by vereis** [comment]
If that's all shall I close the issue?

**Comment by baker-james** [comment]
Thanks for the link @ScottSteiner I didn't think to try archive.org :)
The issue can be closed - from my end anyhow
Thanks
